# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: Gabriel Stevano
  id: Gabriel Stevano
# email: your-email@domain.com
description:
  en: Disclaimer - All content is a Personal Note of Gabriel Stevano, not affiliated to and represent any party. copyright is belongs to Gabriel only
  id: Disclaimer - Semua copyright konten merupakan milik pribadi, dan merupakan catatan pribadi, tidak berafiliasi dan mewakili pihak lain.
index:
  en:
  id: artikel.html
feed:
  en: /feed.xml
  id: /flux.xml
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gabrielstevano.com" # the base hostname & protocol for your site
twitter_username: gabestvn
github_username:  gabestev

# Build settings
markdown: kramdown
